/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_final;

import java.awt.Dimension;
import java.awt.Toolkit;



/**
 *
 * @author Acer
 */
public class NewJFrame extends javax.swing.JFrame {
    private Object jframe;
     //jframe.setSize(1258, 708);

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //setResizable(false);
        setTitle("Cafe de` Pablo");
       
        //setAlwaysOnTop(true);
        //setResizable(false);
        //setVisible(true);
        Toolkit tk=Toolkit.getDefaultToolkit();
        //Dimension size=tk.getScreenSize();
        //setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        
        
        setSize(x,y);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chef = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        contact = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        about = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        feedback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(35, 35, 1258, 708));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/586827a9-e66a-47c2-a501-b5b0b3a71b13_200x200.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 20, 200, 192);

        menu.setBackground(new java.awt.Color(0, 51, 51));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/menu.png"))); // NOI18N
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(220, 370, 230, 220);

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 320, 56, 29);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/shopping-cart.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 370, 240, 220);

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cart");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(800, 320, 42, 29);

        chef.setBackground(new java.awt.Color(0, 51, 51));
        chef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/chef.png"))); // NOI18N
        chef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefActionPerformed(evt);
            }
        });
        getContentPane().add(chef);
        chef.setBounds(1240, 360, 240, 230);

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rate Us");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1290, 310, 77, 29);

        contact.setBackground(new java.awt.Color(0, 51, 51));
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/phone.png"))); // NOI18N
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact);
        contact.setBounds(1260, 750, 250, 220);

        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(790, 690, 76, 29);

        about.setBackground(new java.awt.Color(0, 51, 51));
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/admin.png"))); // NOI18N
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about);
        about.setBounds(690, 750, 260, 220);

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("About");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1350, 700, 60, 29);

        feedback.setBackground(new java.awt.Color(0, 51, 51));
        feedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/rating.png"))); // NOI18N
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });
        getContentPane().add(feedback);
        feedback.setBounds(221, 751, 220, 220);

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Feedback");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 710, 93, 29);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_final/3.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

        Menu1 s= new Menu1();
        s.setVisible(true);
        NewJFrame nv=new NewJFrame();
        nv.setVisible(false);

        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        Contact s= new Contact();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_contactActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        About1 q= new About1();
        q.setVisible(true);

        dispose();
    }//GEN-LAST:event_aboutActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        Feedback s= new Feedback();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_feedbackActionPerformed

    private void chefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefActionPerformed
        RatingForm s= new RatingForm();
        s.setVisible(true);
    }//GEN-LAST:event_chefActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CartGUI s=new CartGUI();
        s.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton chef;
    private javax.swing.JButton contact;
    private javax.swing.JButton feedback;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables
}
